---
title: "Data Exploration"
authors: "Naman Gupta, Brian Zhao, and Dawson Wang"
date: "11/29/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#LIBRARIES
```{r}
library(data.table)
library(geosphere)
library(dplyr)
library(ggplot2)
#allfiles <- list.files()
#csvfiles <- allfiles[2:13]
#csvfiles
#sample_data <- read.csv("SampleCitiBike.csv")
```

#TEAM CLEANING DATA
```{r}
master <- read.csv("new_MASTER_01_data.csv")
master$bikeid <- as.factor(master$bikeid)
master$gender <- as.factor(master$gender)

master$gender <- as.factor(ifelse(master$gender == "0", "Unknown", ifelse(master$gender == "1", "Male", "Female")))
master$X.1 <- NULL
master$X <- NULL
str(master)
summary(master)

masterstart <- as.data.frame(matrix(nrow = 205517, ncol = 0))
masterstart$startlong <- as.numeric(master$start.station.longitude)
masterstart$startlat <- as.numeric(master$start.station.latitude)

masterend <- as.data.frame(matrix(nrow = 205517, ncol = 0))
masterend$endlong <- master$end.station.longitude
masterend$endlat <- master$end.station.latitude

master$distanceH <- distHaversine(masterstart, masterend, r=6378137)

str(master)
summary(master)
```



#commenting out for knitting purposes
```{r, cache=TRUE, eval = FALSE}
data <- rbindlist(lapply(csvfiles,fread))
```

#commenting out for knitting purposes
```{r, cache=TRUE, eval = FALSE}
#create random 5% sample of data
sample_data <- sample_frac(data, 0.01)
write.csv(sample_data,'sample_01_data.csv')
str(read.csv("sample_01_data.csv"))
```



#commenting out for knitting purposes
```{r}
#library(data.table)
#library(dplyr)
#library(ggplot2)
#allfiles <- list.files()
#csvfiles <- allfiles[1:12]
#csvfiles
sample_data <- read.csv("SampleCitiBike.csv")
```

#commenting out for knitting purposes
```{r, cache=TRUE}
#data <- rbindlist(lapply(csvfiles,fread))
```

#commenting out for knitting purposes
```{r, cache=TRUE}
#create random 5% sample of data
#sample_data <- sample_frac(data, 0.01)
```

#cleaning the data
```{r, cache=TRUE}
#view summary and structure
summary(sample_data)
str(sample_data)

#convert columns to factors as needed
sample_data$`start station id` <- as.factor(sample_data$`start station id`)
sample_data$`start station name` <- as.factor(sample_data$`start station name`)
sample_data$`end station id` <- as.factor(sample_data$`end station id`)
sample_data$`end station name` <- as.factor(sample_data$`end station name`)
sample_data$bikeid <- as.factor(sample_data$bikeid)
sample_data$usertype <- as.factor(sample_data$usertype)
sample_data$gender <- as.factor(sample_data$gender)
sample_data$gender <- as.factor(ifelse(sample_data$gender == "0", "Unknown", ifelse(sample_data$gender == "1", "Male", "Female")))

#review summary and structure
summary(sample_data)
str(sample_data)
```