---
title: "NamanPlayground"
author: "Naman Gupta"
date: "12/1/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(data.table)
library(dplyr)
library(ggplot2)
library(geosphere)
library(lubridate)
```

```{r}
masterdata <- read.csv("new_MASTER_01_data.csv")
#sample_01_data <- read.csv("sample_01_data.csv")
#masterdata$newStartTime <- sample_01_data$starttime
#masterdata$newStopTime <- sample_01_data$stoptime
#write.csv(masterdata,"new_MASTER_01_data.csv")
  
summary(masterdata)
str(masterdata)
#is the date data gone?
#summary(read.csv("sample_01_data.csv"))
#convert columns to factors as needed

masterdata$bikeid <- as.factor(masterdata$bikeid)
masterdata$gender <- as.factor(masterdata$gender)

masterdata$gender <- as.factor(ifelse(masterdata$gender == "0", "Unknown", ifelse(masterdata$gender == "1", "Male", "Female")))
masterdata$X <- NULL
masterdata$starttime <- NULL
masterdata$stoptime <- NULL

masterdata$newStartTime = as.POSIXct(strptime(masterdata$newStartTime, "%Y-%m-%d %H:%M:%S"))
masterdata$newStopTime = as.POSIXct(strptime(masterdata$newStopTime, "%Y-%m-%d %H:%M:%S"))

masterdata$newStartDate <- as.Date(masterdata$newStartTime)
masterdata$newStopDate <- as.Date(masterdata$newStopTime)

#distance
masterstart <- as.data.frame(matrix(nrow = 205517, ncol = 0))
masterstart$startlong <- as.numeric(masterdata$start.station.longitude)
masterstart$startlat <- as.numeric(masterdata$start.station.latitude)

masterend <- as.data.frame(matrix(nrow = 205517, ncol = 0))
masterend$endlong <- masterdata$end.station.longitude
masterend$endlat <- masterdata$end.station.latitude

masterdata$distanceH <- distHaversine(masterstart, masterend, r=6378137)

masterend <- NULL
masterstart <- NULL

#new age classification
masterdata$agegroup <- as.factor(ifelse(masterdata$birth.year >= 2000, "GenZ", ifelse(masterdata$birth.year >= 1981, "Millennial", ifelse(masterdata$birth.year >= 1965, "GenX", ifelse(masterdata$birth.year >= 1946, "Boomer", ifelse(masterdata$birth.year >= 1928, "Silent", "VeryOld"))))))

#order factor levels for visualizations
masterdata$agegroup <- factor(masterdata$agegroup, levels = c("GenZ", "Millennial", "GenX", "Boomer", "Silent", "VeryOld"))

#new columns for months for visualizations
masterdata$startMonth <- month(masterdata$newStartDate)
masterdata$stopMonth <- month(masterdata$newStopDate)
masterdata$startMonthFactor <- as.factor(month(masterdata$newStartDate))
masterdata$stopMonthFactor <- as.factor(month(masterdata$newStopDate))
str(masterdata)
summary(masterdata)
```

```{r}
#average precip per month
#facet wrap month, against count of number of rides as y variable. x = average precip, colour = gender
#categorize birth year into age groups. Facet wrap or colour by age groups
#rain vs trip length (end time - start time)
#bar plot of busy/not-busy stations on rainy days
#randomly try the same plot across a few select dates


ggplot(data=masterdata, aes(x=newStartDate, y=tripduration, colour=gender)) + geom_point()

#newStartDate vs tripduration by gender
ggplot(data=masterdata[masterdata$tripduration < 10000,], aes(x=newStartDate, y=tripduration, colour=gender)) + geom_point()

ggplot(data=masterdata[masterdata$tripduration < 10000,], aes(x=newStartDate, y=tripduration, colour=gender)) + geom_smooth()

ggplot(data=masterdata[masterdata$tripduration < 10000,], aes(x=newStartDate, y=tripduration, colour=gender)) + geom_violin()

ggplot(data=masterdata[masterdata$tripduration < 10000,], aes(x=newStartDate, y=tripduration, colour=gender)) + geom_boxplot()

#newStartDate vs tripduration by usertype
ggplot(data=masterdata[masterdata$tripduration < 10000,], aes(x=newStartDate, y=tripduration, colour=usertype)) + geom_point()

ggplot(data=masterdata[masterdata$tripduration < 10000,], aes(x=newStartDate, y=tripduration, colour=usertype)) + geom_smooth()

ggplot(data=masterdata[masterdata$tripduration < 10000,], aes(x=newStartDate, y=tripduration, colour=usertype)) + geom_violin()

ggplot(data=masterdata[masterdata$tripduration < 10000,], aes(x=newStartDate, y=tripduration, colour=usertype)) + geom_boxplot()
```

```{r}
#prcp vs tripduration by gender
ggplot(data=masterdata[masterdata$tripduration < 10000,], aes(x=PRCP, y=tripduration, colour=gender)) + geom_point()

ggplot(data=masterdata[masterdata$tripduration < 10000,], aes(x=PRCP, y=tripduration, colour=gender)) + geom_smooth()

ggplot(data=masterdata[masterdata$tripduration < 10000,], aes(x=PRCP, y=tripduration, colour=gender)) + geom_violin()

ggplot(data=masterdata[masterdata$tripduration < 10000,], aes(x=PRCP, y=tripduration, colour=gender)) + geom_boxplot()

#prcp vs tripduration by usertype
ggplot(data=masterdata[masterdata$tripduration < 10000,], aes(x=PRCP, y=tripduration, colour=usertype)) + geom_point()

ggplot(data=masterdata[masterdata$tripduration < 10000,], aes(x=PRCP, y=tripduration, colour=usertype)) + geom_smooth()

ggplot(data=masterdata[masterdata$tripduration < 10000,], aes(x=PRCP, y=tripduration, colour=usertype)) + geom_violin()

ggplot(data=masterdata[masterdata$tripduration < 10000,], aes(x=PRCP, y=tripduration, colour=usertype)) + geom_boxplot()
```

```{r}
#prcp vs tripduration by gender
ggplot(data=masterdata[masterdata$tripduration < 10000,], aes(x=PRCP, y=distanceH, colour=gender)) + geom_point()

ggplot(data=masterdata[masterdata$tripduration < 10000,], aes(x=PRCP, y=distanceH, colour=gender)) + geom_smooth()

ggplot(data=masterdata[masterdata$tripduration < 10000,], aes(x=PRCP, y=distanceH, colour=gender)) + geom_violin()

ggplot(data=masterdata[masterdata$tripduration < 10000,], aes(x=PRCP, y=distanceH, colour=gender)) + geom_boxplot()

#prcp vs tripduration by usertype
ggplot(data=masterdata[masterdata$tripduration < 10000,], aes(x=PRCP, y=distanceH, colour=usertype)) + geom_point()

ggplot(data=masterdata[masterdata$tripduration < 10000,], aes(x=PRCP, y=distanceH, colour=usertype)) + geom_smooth()

ggplot(data=masterdata[masterdata$tripduration < 10000,], aes(x=PRCP, y=distanceH, colour=usertype)) + geom_violin()

ggplot(data=masterdata[masterdata$tripduration < 10000,], aes(x=PRCP, y=distanceH, colour=usertype)) + geom_boxplot()
```

```{r}
averagePRCPMonthly <- tapply(masterdata$PRCP,masterdata$startMonthFactor,mean,)
plot(averagePRCPMonthly,xlab="Month",ylab="Average PRCP")

averageTripDurationMonthly <- tapply(masterdata$tripduration,masterdata$startMonthFactor,mean,)
plot(averageTripDurationMonthly,xlab="Month",ylab="Average Trip Duration")

numTripsMonthly <- table(masterdata$startMonth)

ggplot(,aes(x=averagePRCPMonthly, y=averageTripDurationMonthly)) + geom_point()

ggplot(,aes(x=averagePRCPMonthly, y=numTripsMonthly)) + geom_point()

ggplot(data=masterdata, aes(x=PRCP,y=tripduration)) + geom_point() + facet_wrap(~ startMonthFactor)

ggplot(data=masterdata[masterdata$tripduration < 10000,], aes(x=PRCP,y=tripduration)) + geom_smooth() + facet_wrap(~ startMonthFactor)

ggplot(data=masterdata[masterdata$tripduration < 10000,], aes(x=PRCP,y=tripduration,colour=usertype)) + geom_smooth() + facet_wrap(~ startMonthFactor)

ggplot(data=masterdata[masterdata$tripduration < 10000,], aes(x=PRCP,y=tripduration,colour=gender)) + geom_smooth() + facet_wrap(~ startMonthFactor)

ggplot(data=masterdata[masterdata$tripduration < 10000,], aes(x=PRCP,y=tripduration,colour=gender)) + geom_smooth() + facet_wrap(~ usertype)

ggplot(data=masterdata[masterdata$tripduration < 10000,], aes(x=PRCP,y=tripduration,colour=usertype)) + geom_smooth() + facet_wrap(~ gender)

```
```{r}
ggplot(data=masterdata, aes(x=PRCP,y=distanceH)) + geom_point() + facet_wrap(~ startMonthFactor)

ggplot(data=masterdata[masterdata$tripduration < 10000,], aes(x=PRCP,y=distanceH)) + geom_smooth() + facet_wrap(~ startMonthFactor)

ggplot(data=masterdata[masterdata$tripduration < 10000,], aes(x=PRCP,y=distanceH,colour=usertype)) + geom_smooth() + facet_wrap(~ startMonthFactor)

ggplot(data=masterdata[masterdata$tripduration < 10000,], aes(x=PRCP,y=distanceH,colour=gender)) + geom_smooth() + facet_wrap(~ startMonthFactor)

ggplot(data=masterdata[masterdata$tripduration < 10000,], aes(x=PRCP,y=distanceH,colour=gender)) + geom_smooth() + facet_wrap(~ usertype)

ggplot(data=masterdata[masterdata$tripduration < 10000,], aes(x=PRCP,y=distanceH,colour=usertype)) + geom_smooth() + facet_wrap(~ gender)
```