---
title: "TO404_FinalProject"
author: "Brian Zhao"
date: "12/4/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# TO 404 Final Project

## Libraries
```{r}
library(dplyr)
library(ggplot2)
library(geosphere)
library(data.table)
```

## Read Data
```{r, cache=TRUE, eval = FALSE}
# Read Original CitiBike Data
sampleData <- read.csv("SampleCitiBike.csv")
# Create 1% Random Sample
sampleData_01 <- sample_frac(data, 0.01)
# Write to New CSV
write.csv(sampleData_01, 'sample_01_data.csv')
# Weather Data Manually Appended in new_MASTER_01_data.csv
```

```{r}
master <- read.csv("new_MASTER_01_data.csv")
```

## Clean Data
```{r}
# Explore Data
str(master)
summary(master)

# Remove Identifier Column
master$X <- NULL

# Assign Factors
master$bikeid <- as.factor(master$bikeid)
master$gender <- as.factor(master$gender)
master$gender <- as.factor(ifelse(master$gender == "0", "Unknown", ifelse(master$gender == "1", "Male", "Female")))

# Distance
masterstart <- as.data.frame(matrix(nrow = 205517, ncol = 0))
masterstart$startlong <- as.numeric(master$start.station.longitude)
masterstart$startlat <- as.numeric(master$start.station.latitude)

masterend <- as.data.frame(matrix(nrow = 205517, ncol = 0))
masterend$endlong <- master$end.station.longitude
masterend$endlat <- master$end.station.latitude

master$distanceH <- distHaversine(masterstart, masterend, r=6378137)

# Date
master$newStartTime = as.POSIXct(strptime(master$newStartTime, "%Y-%m-%d %H:%M:%S"))
master$newStopTime = as.POSIXct(strptime(master$newStopTime, "%Y-%m-%d %H:%M:%S"))

# Snow
master$roundedSNOW <- floor(master$SNOW)

# Check Data
str(master)
summary(master)
```

# Weather

## Snow
*Effects of Snow on:*
- Ride Distance (Customer vs. Subscriber)
```{r}
ggplot(data=master[master$distanceH < 10000,], aes(x=SNOW, y=distanceH, colour=usertype)) + geom_smooth()

ggplot(data=master[master$distanceH < 10000,], aes(x=SNOW, y=distanceH, colour=usertype)) + geom_point(alpha = 0.5) + geom_jitter()
ggplot(data=master[master$distanceH < 10000,], aes(x=roundedSNOW, y=distanceH, colour=usertype)) + geom_point(alpha = 0.5) + geom_jitter()
```

- Ride Duration
```{r}
ggplot(data=master[master$tripduration < 10000,], aes(x=SNOW, y=tripduration, colour=usertype)) + geom_smooth()

ggplot(data=master[master$tripduration < 10000,], aes(x=SNOW, y=tripduration, colour=usertype)) + geom_point(alpha = 0.5) + geom_jitter()
ggplot(data=master[master$tripduration < 10000,], aes(x=roundedSNOW, y=tripduration, colour=usertype)) + geom_point(alpha = 0.5) + geom_jitter()

totalRides <- tapply(master$tripduration, master$SNOW, mean, na.rm = TRUE)
barplot(totalRides)
totalRides <- tapply(master$tripduration, master$roundedSNOW, mean, na.rm = TRUE)
barplot(totalRides)
```

- Total Rides
```{r}
# Raw Data
ggplot(data=master, aes(x=SNOW)) + geom_bar()
ggplot(data=master[master$SNOW > 0, ], aes(x=SNOW)) + geom_bar()

# Rounded Values
ggplot(data=master, aes(x=roundedSNOW)) + geom_bar()
ggplot(data=master[master$roundedSNOW > 0, ], aes(x=roundedSNOW)) + geom_bar()

```

- Demographics (Female vs. Male, Age)
```{r}
ggplot(data=master[master$tripduration < 10000,], aes(x=SNOW, y=tripduration, colour=gender)) + geom_point(alpha = 0.25) + geom_jitter()
ggplot(data=master[master$tripduration < 10000,], aes(x=roundedSNOW, y=tripduration, colour=gender)) + geom_point(alpha = 0.25) + geom_jitter()
```

